services:
  mongo:
    container_name: bricks-battle-mongodb
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=pass
  frontend:
    container_name: bricks-battle-app
    image: atakowiec/bricks-battle-game:app
    volumes:
      - /app/frontend/node_modules
    ports:
      - "8000:80"
    depends_on:
      - mongo
  backend:
    container_name: bricks-battle-server
    image: atakowiec/bricks-battle-game:server
    environment:
      - JWT_SECRET=4tg4uigq3gq3478g34uhg3478gh34uifh378f3h4uif34ui
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_USER=root
      - MONGO_PASS=pass
      - CLIENT_URL=http://localhost:8000
    volumes:
      - /app/backend/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - mongo